### ISSUE TITLE
undefined method error with 1.2.4

### ISSUE THREAD

**Issue by njia** [boxen/puppet-iterm2#40]
Hi there

Not sure why but I am getting following error when I upgrade boxen from 3.7 to 3.10.1 and iterm2 to 1.2.4.

No problem with iterm2 1.2.3

thanks

```
bundle exec librarian-puppet install --clean --verbose
blah blah ....
[Librarian] Installing imagemagick/1.3.0 <boxen/puppet-imagemagick>
[Librarian] Installing inifile/1.1.1 <puppetlabs/puppetlabs-inifile>
[Librarian] Installing iterm2/1.2.4 <boxen/puppet-iterm2>
/opt/rubies/1.8.7-p358/lib/ruby/1.8/fileutils.rb:1414:in `fu_each_src_dest0': undefined method `to_str' for nil:NilClass (NoMethodError)
    from /opt/rubies/1.8.7-p358/lib/ruby/1.8/fileutils.rb:1400:in `fu_each_src_dest'
    from /opt/rubies/1.8.7-p358/lib/ruby/1.8/fileutils.rb:423:in `cp_r'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-1.0.9/lib/librarian/puppet/util.rb:21:in `cp_r'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-1.0.9/lib/librarian/puppet/source/githubtarball/repo.rb:56:in `install_version!'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-1.0.9/lib/librarian/puppet/source/githubtarball.rb:84:in `install!'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-0.1.2/lib/librarian/manifest.rb:101:in `install!'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-0.1.2/lib/librarian/action/install.rb:49:in `install_manifests'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `each'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `install_manifests'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-0.1.2/lib/librarian/action/install.rb:39:in `perform_installation'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-0.1.2/lib/librarian/action/install.rb:12:in `run'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-1.0.9/lib/librarian/puppet/cli.rb:94:in `install!'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-1.0.9/lib/librarian/puppet/cli.rb:69:in `install'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/thor-0.19.1/lib/thor/command.rb:27:in `__send__'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
    from /opt/boxen/repo/.bundle/ruby/1.8/gems/librarian-puppet-1.0.9/bin/librarian-puppet:7
    from /opt/boxen/repo/.bundle/ruby/1.8/bin/librarian-puppet:19:in `load'
    from /opt/boxen/repo/.bundle/ruby/1.8/bin/librarian-puppet:19
```

**Comment by tarebyte** [comment]
I'll check it out today @njia thanks for the heads up!

**Comment by jacobbednarz** [comment]
@njia are you able to confirm if this is still an issue on the latest? I'm going to close this but do let me know if this is still a problem and I'll take a look.
